version: "3"
services:
   webclient:
    image: ghcr.io/asciiflix/webclient:${VERSION}
    container_name: asciiflix_webclient
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.asciiflix_webclient.rule=Host(`asciiflix.de`) || Host(`www.asciiflix.de`)"
      - "traefik.http.routers.asciiflix_webclient.entrypoints=websecure"
      - "traefik.http.routers.asciiflix_webclient.tls.certresolver=myhttpchallenge"
    networks:
      - proxy

networks:
  proxy:
    external: true
