name: deployment

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: v.

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: VERSION=${{ steps.tag_version.outputs.new_tag }}
          push: true
          tags: |
            ghcr.io/asciiflix/webclient:latest
            ghcr.io/asciiflix/webclient:${{ steps.tag_version.outputs.new_tag }}
          labels: asciiflix/webclient

      - name: Redeploy Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: ./deploy_web.sh ${{ steps.tag_version.outputs.new_tag }}